// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortenerClient is the client API for Shortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortenerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetShort(ctx context.Context, in *GetShortRequest, opts ...grpc.CallOption) (*GetShortResponse, error)
	SetShort(ctx context.Context, in *SetShortRequest, opts ...grpc.CallOption) (*SetShortResponse, error)
	APIUserURLsDelete(ctx context.Context, in *APIUserURLsDeleteRequest, opts ...grpc.CallOption) (*APIUserURLsDeleteResponse, error)
	APIUserUrls(ctx context.Context, in *APIUserUrlsRequest, opts ...grpc.CallOption) (*APIUserUrlsResponse, error)
	APIBatch(ctx context.Context, in *APIBatchRequest, opts ...grpc.CallOption) (*APIBatchResponse, error)
	APIShorten(ctx context.Context, in *APIShortenRequest, opts ...grpc.CallOption) (*APIShortenResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
}

type shortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerClient(cc grpc.ClientConnInterface) ShortenerClient {
	return &shortenerClient{cc}
}

func (c *shortenerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetShort(ctx context.Context, in *GetShortRequest, opts ...grpc.CallOption) (*GetShortResponse, error) {
	out := new(GetShortResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/GetShort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) SetShort(ctx context.Context, in *SetShortRequest, opts ...grpc.CallOption) (*SetShortResponse, error) {
	out := new(SetShortResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/SetShort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) APIUserURLsDelete(ctx context.Context, in *APIUserURLsDeleteRequest, opts ...grpc.CallOption) (*APIUserURLsDeleteResponse, error) {
	out := new(APIUserURLsDeleteResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/APIUserURLsDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) APIUserUrls(ctx context.Context, in *APIUserUrlsRequest, opts ...grpc.CallOption) (*APIUserUrlsResponse, error) {
	out := new(APIUserUrlsResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/APIUserUrls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) APIBatch(ctx context.Context, in *APIBatchRequest, opts ...grpc.CallOption) (*APIBatchResponse, error) {
	out := new(APIBatchResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/APIBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) APIShorten(ctx context.Context, in *APIShortenRequest, opts ...grpc.CallOption) (*APIShortenResponse, error) {
	out := new(APIShortenResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/APIShorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, "/shortener.Shortener/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServer is the server API for Shortener service.
// All implementations must embed UnimplementedShortenerServer
// for forward compatibility
type ShortenerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetShort(context.Context, *GetShortRequest) (*GetShortResponse, error)
	SetShort(context.Context, *SetShortRequest) (*SetShortResponse, error)
	APIUserURLsDelete(context.Context, *APIUserURLsDeleteRequest) (*APIUserURLsDeleteResponse, error)
	APIUserUrls(context.Context, *APIUserUrlsRequest) (*APIUserUrlsResponse, error)
	APIBatch(context.Context, *APIBatchRequest) (*APIBatchResponse, error)
	APIShorten(context.Context, *APIShortenRequest) (*APIShortenResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	mustEmbedUnimplementedShortenerServer()
}

// UnimplementedShortenerServer must be embedded to have forward compatible implementations.
type UnimplementedShortenerServer struct {
}

func (UnimplementedShortenerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedShortenerServer) GetShort(context.Context, *GetShortRequest) (*GetShortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShort not implemented")
}
func (UnimplementedShortenerServer) SetShort(context.Context, *SetShortRequest) (*SetShortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetShort not implemented")
}
func (UnimplementedShortenerServer) APIUserURLsDelete(context.Context, *APIUserURLsDeleteRequest) (*APIUserURLsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIUserURLsDelete not implemented")
}
func (UnimplementedShortenerServer) APIUserUrls(context.Context, *APIUserUrlsRequest) (*APIUserUrlsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIUserUrls not implemented")
}
func (UnimplementedShortenerServer) APIBatch(context.Context, *APIBatchRequest) (*APIBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIBatch not implemented")
}
func (UnimplementedShortenerServer) APIShorten(context.Context, *APIShortenRequest) (*APIShortenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIShorten not implemented")
}
func (UnimplementedShortenerServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedShortenerServer) mustEmbedUnimplementedShortenerServer() {}

// UnsafeShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortenerServer will
// result in compilation errors.
type UnsafeShortenerServer interface {
	mustEmbedUnimplementedShortenerServer()
}

func RegisterShortenerServer(s grpc.ServiceRegistrar, srv ShortenerServer) {
	s.RegisterService(&Shortener_ServiceDesc, srv)
}

func _Shortener_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetShort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/GetShort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetShort(ctx, req.(*GetShortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_SetShort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetShortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).SetShort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/SetShort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).SetShort(ctx, req.(*SetShortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_APIUserURLsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIUserURLsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).APIUserURLsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/APIUserURLsDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).APIUserURLsDelete(ctx, req.(*APIUserURLsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_APIUserUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIUserUrlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).APIUserUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/APIUserUrls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).APIUserUrls(ctx, req.(*APIUserUrlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_APIBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).APIBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/APIBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).APIBatch(ctx, req.(*APIBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_APIShorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).APIShorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/APIShorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).APIShorten(ctx, req.(*APIShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.Shortener/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shortener_ServiceDesc is the grpc.ServiceDesc for Shortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortener.Shortener",
	HandlerType: (*ShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Shortener_Ping_Handler,
		},
		{
			MethodName: "GetShort",
			Handler:    _Shortener_GetShort_Handler,
		},
		{
			MethodName: "SetShort",
			Handler:    _Shortener_SetShort_Handler,
		},
		{
			MethodName: "APIUserURLsDelete",
			Handler:    _Shortener_APIUserURLsDelete_Handler,
		},
		{
			MethodName: "APIUserUrls",
			Handler:    _Shortener_APIUserUrls_Handler,
		},
		{
			MethodName: "APIBatch",
			Handler:    _Shortener_APIBatch_Handler,
		},
		{
			MethodName: "APIShorten",
			Handler:    _Shortener_APIShorten_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Shortener_Stat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shortener.proto",
}
