// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storable is an autogenerated mock type for the Storable type
type Storable struct {
	mock.Mock
}

// AsyncSaver provides a mock function with given fields:
func (_m *Storable) AsyncSaver() {
	_m.Called()
}

// BatchSet provides a mock function with given fields: ctx, data, userID
func (_m *Storable) BatchSet(ctx context.Context, data []byte, userID int) ([]byte, error) {
	ret := _m.Called(ctx, data, userID)

	if len(ret) == 0 {
		panic("no return value specified for BatchSet")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, int) ([]byte, error)); ok {
		return rf(ctx, data, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, int) []byte); ok {
		r0 = rf(ctx, data, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, int) error); ok {
		r1 = rf(ctx, data, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields:
func (_m *Storable) Destroy() {
	_m.Called()
}

// Get provides a mock function with given fields: ctx, shortLink
func (_m *Storable) Get(ctx context.Context, shortLink string) (string, bool, error) {
	ret := _m.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, shortLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortLink)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, shortLink)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, shortLink)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// HandleUserUrls provides a mock function with given fields: ctx, userID
func (_m *Storable) HandleUserUrls(ctx context.Context, userID int) ([]byte, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for HandleUserUrls")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]byte, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleUserUrlsDelete provides a mock function with given fields: links, userID
func (_m *Storable) HandleUserUrlsDelete(links string, userID int) {
	_m.Called(links, userID)
}

// Init provides a mock function with given fields:
func (_m *Storable) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ping provides a mock function with given fields: ctx
func (_m *Storable) Ping(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, originalLink, shortLink, hashLink, userID
func (_m *Storable) Set(ctx context.Context, originalLink string, shortLink string, hashLink string, userID int) error {
	ret := _m.Called(ctx, originalLink, shortLink, hashLink, userID)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) error); ok {
		r0 = rf(ctx, originalLink, shortLink, hashLink, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorable creates a new instance of Storable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storable {
	mock := &Storable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
