// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/MaximMNsk/go-url-shortener/server/config"

	mock "github.com/stretchr/testify/mock"
)

// Storable is an autogenerated mock type for the Storable type
type Storable struct {
	mock.Mock
	Link      string
	ShortLink string
	ID        string
}

// AsyncSaver provides a mock function with given fields:
func (_m *Storable) AsyncSaver() {
	_m.Called()
}

// BatchSet provides a mock function with given fields:
func (_m *Storable) BatchSet() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchSet")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields:
func (_m *Storable) Destroy() {
	_m.Called()
}

// Get provides a mock function with given fields:
func (_m *Storable) Get() (string, bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func() (string, bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// HandleUserUrls provides a mock function with given fields:
func (_m *Storable) HandleUserUrls() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HandleUserUrls")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleUserUrlsDelete provides a mock function with given fields:
func (_m *Storable) HandleUserUrlsDelete() {
	_m.Called()
}

// Init provides a mock function with given fields: link, shortLink, id, isDeleted, ctx, cfg
func (_m *Storable) Init(link string, shortLink string, id string, isDeleted bool, ctx context.Context, cfg config.OuterConfig) error {
	ret := _m.Called(link, shortLink, id, isDeleted, ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, bool, context.Context, config.OuterConfig) error); ok {
		r0 = rf(link, shortLink, id, isDeleted, ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *Storable) Ping() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields:
func (_m *Storable) Set() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorable creates a new instance of Storable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storable {
	mock := &Storable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
